[package]
name = "png_pong"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"

categories = ["multimedia::encoding", "multimedia::images"]
description = "Reading and writing PNG/APNG files without system dependencies."
documentation = "https://docs.rs/png_pong/"
homepage = "https://crates.rs/crates/png_pong/"
include = ["src/**/*", "COPYRIGHT", "README.md", "Cargo.toml"]
keywords = ["png", "lodepng", "encoder", "decoder", "apng"]
license = "Zlib / MIT OR BSL-1.0"
readme = "README.md"
repository = "https://github.com/LordAldaron/png_pong.git"

[badges]
travis-ci = { repository = "LordAldaron/png_pong" }

[dependencies]
pix = "0.8"
miniz_oxide = { optional = true, version = "0.3" }

[profile.test]
opt-level = 2

[profile.dev]
opt-level = 2

[features]
default = ["flate"]
flate = ["miniz_oxide"]
