# PNG Pong
#
# Copyright © 2019-2020 Jeron Aldaron Lau
# Copyright © 2014-2017 Kornel Lesiński
# Copyright © 2005-2016 Lode Vandevenne
# 
# Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
# https://apache.org/licenses/LICENSE-2.0>, or the Zlib License, <LICENSE-ZLIB
# or http://opensource.org/licenses/Zlib>, at your option. This file may not be
# copied, modified, or distributed except according to those terms.

[package]
name = "png_pong"
version = "0.2.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "Apache-2.0 OR Zlib"

description = "A pure Rust PNG/APNG encoder & decoder"
repository = "https://github.com/RedAldaron/png_pong"
documentation = "https://docs.rs/png_pong"
homepage = "https://github.com/RedAldaron/png_pong/blob/master/CHANGELOG.md"
include = ["Cargo.toml", "LICENSE-ZLIB", "LICENSE-APACHE", "src/*"]
categories = ["multimedia::encoding", "multimedia::images"]
keywords = ["png", "lodepng", "encoder", "decoder", "apng"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "RedAldaron/png_pong" }
is-it-maintained-issue-resolution = { repository = "RedAldaron/png_pong" }
is-it-maintained-open-issues = { repository = "RedAldaron/png_pong" }
maintenance = { status = "actively-developed" }

[dependencies.pix]
version = "0.10"

[dependencies.miniz_oxide]
version = "0.3"
optional = true

[build-dependencies]

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"

[profile.test]
opt-level = 2

[profile.dev]
opt-level = 2

[features]
default = ["flate"]
flate = ["miniz_oxide"]
docs-rs = []
