# png-pong
#
# Copyright © 2019-2020 Jeron Aldaron Lau
# Copyright © 2014-2017 Kornel Lesiński
# Copyright © 2005-2016 Lode Vandevenne
# 
# Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
# https://apache.org/licenses/LICENSE-2.0>, or the Zlib License, <LICENSE-ZLIB
# or http://opensource.org/licenses/Zlib>, at your option. This file may not be
# copied, modified, or distributed except according to those terms.

[package]
name = "png-pong"
version = "0.2.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "Apache-2.0 OR Zlib"

description = "Read and write PNG/APNG files without system dependencies."
repository = "https://github.com/RedAldaron/png-pong"
documentation = "https://docs.rs/png-pong"
homepage = "https://github.com/RedAldaron/png-pong/blob/master/CHANGELOG.md"
include = ["Cargo.toml", "LICENSE-ZLIB", "LICENSE-APACHE", "src/*"]
categories = ["multimedia::encoding", "multimedia::images"]
keywords = ["png", "lodepng", "encoder", "decoder", "apng"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "RedAldaron/png-pong" }
is-it-maintained-issue-resolution = { repository = "RedAldaron/png-pong" }
is-it-maintained-open-issues = { repository = "RedAldaron/png-pong" }
maintenance = { status = "actively-developed" }

[dependencies.pix]
version = "0.10"

[depedencies.miniz_oxide]
version = "0.3"
optional = true

[build-dependencies]

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"

[profile.test]
opt-level = 2

[profile.dev]
opt-level = 2

[features]
default = ["flate"]
external_doc = [] # For docs.rs documentation (uses nightly)
flate = ["miniz_oxide"]
